version: "3"

services:
  tidarr:
    build: './docker'
    container_name: 'tidarr'
    ports:
      - 8484:8484
    volumes:
      - ./docker/mnt/config:/home/app/standalone/shared
      - ./docker/mnt/download/albums:/home/app/standalone/download/albums
      - ./docker/mnt/download/tracks:/home/app/standalone/download/tracks
      - .:/home/app/standalone # only used in dev environment
    restart: 'unless-stopped'
    environment:
      - ENABLE_BEETS=true
      - NEXT_PUBLIC_TIDAL_SEARCH_TOKEN= # optional
      - NEXT_PUBLIC_TIDAL_COUNTRY_CODE=FR # optional
     

