version: "3"

services:
  tidarr:
    build: './docker'
    container_name: 'tidarr'
    ports:
      - 8484:8484
    volumes:
      - ./settings/.tidal-dl.token.json:/root/.tidal-dl.token.json
      - ./settings/.tidal-dl.json:/root/.tidal-dl.json
      - ./settings/beets-config.yml:/root/beets-config.yml
      - ./download/albums:/home/app/standalone/download/albums
      - ./download/tracks:/home/app/standalone/download/tracks
      - .:/home/app/standalone # only used in dev environment
    restart: 'unless-stopped'
    environment:
      - ENABLE_BEETS=true
      - NEXT_PUBLIC_TIDAL_SEARCH_TOKEN= # optional
      - NEXT_PUBLIC_TIDAL_COUNTRY_CODE=FR # optional
     

