version: "3"

services:
  node:
    build: '.'
    container_name: 'tidarr'
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./settings/.tidal-dl.token.json:/root/.tidal-dl.token.json
      - ./settings/.tidal-dl.json:/root/.tidal-dl.json
      - ./download:/home/app/standalone/download
    restart: 'unless-stopped'
    environment:
      - NEXT_PUBLIC_TIDAL_SEARCH_TOKEN=
      - NEXT_PUBLIC_TIDAL_COUNTRY_CODE=
     

