version: "3"

services:
  tidarr-front:
    build: './docker'
    container_name: 'tidarr-front'
    ports:
      - 8484:8484
    volumes:
      - .:/home/app/standalone # only used in dev environment
    restart: 'unless-stopped'
    environment:
      - NEXT_PUBLIC_TIDAL_SEARCH_TOKEN= # optional
      - NEXT_PUBLIC_TIDAL_COUNTRY_CODE= # optional
#      - NEXT_PUBLIC_TIDARR_API_URL=true

     

