plugins: fetchart embedart ftintitle permissions convert scrub missing mbsync plexupdate
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: %asciify{$albumartist}/$original_year - %asciify{$album}%aunique{}/$track - %asciify{$title}
    singleton: Non-Album/%asciify{$artist} - %asciify{$title}
    comp: Compilations/%asciify{$album}%aunique{}/$track - %asciify{$title}
    albumtype_soundtrack: Soundtracks/%asciify{$album}%aunique{}/$track - %asciify{$title}

import:
    write: yes
    copy: no
    duplicate_action: remove
    move: yes
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    from_scratch: yes
    log: /home/app/standalone/settings/beets/beet.log

match:
    strong_rec_thresh: 0.1
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

chroma:
    auto: yes

lastgenre:
    auto: yes
    fallback: ''
    source: album

embedart:
    auto: yes
    remove_art_file: yes

permissions:
    file: 644
    dir: 755

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

mpd:
    host: 192.168.0.50
    port: 6600
    # password:

replaygain:
    auto: yes
    overwrite: yes

scrub:
    auto: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337

plex:
    host: 192.168.1.20
    port: 32400
    token: 544czRJ-En3odTw2VQic